import { CONFIG } from './config.js';
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const supabase=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const DEFAULT_CATEGORY='Uncategorized';
let docs=[];

function status(s){const e=$('statusText');if(e)e.textContent=s;}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function cat(v){return String(v||DEFAULT_CATEGORY).trim()||DEFAULT_CATEGORY;}
function safe(v='SNT'){return String(v).replace(/[^A-Za-z0-9._-]+/g,'_').slice(0,100)||'SNT';}
function randomToken(){const a=new Uint8Array(32);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function driveId(v=''){let m=String(v).match(/\/file\/d\/([A-Za-z0-9_-]+)/);if(m)return m[1];m=String(v).match(/[?&]id=([A-Za-z0-9_-]+)/);return m?m[1]:'';}
function studentUrl(d){const u=new URL('./index.html',location.href);u.hash=`t=${d.student_token}`;return u.toString();}
async function copy(t){try{await navigator.clipboard.writeText(t);}catch{const x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove();}}
async function token(){const {data}=await supabase.auth.getSession();const t=data?.session?.access_token;if(!t)throw new Error('Teacher sign-in required.');return t;}
async function headers(extra={}){return {Authorization:`Bearer ${await token()}`,apikey:CONFIG.SUPABASE_PUBLISHABLE_KEY,...extra};}
function apiUrl(doc,action,p={}){const u=new URL(`${CONFIG.SUPABASE_URL}/functions/v1/${CONFIG.API_FUNCTION}`);u.searchParams.set('doc',doc);u.searchParams.set('action',action);for(const[k,v]of Object.entries(p))u.searchParams.set(k,String(v));return u.toString();}
async function api(doc,action,p={}){const r=await fetch(apiUrl(doc,action,p),{headers:await headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}
function stamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}_${p(d.getHours())}-${p(d.getMinutes())}`;}
function imageExt(m=''){return m==='image/jpeg'?'jpg':m==='image/webp'?'webp':m==='image/gif'?'gif':'png';}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000);}

function ensureUI(){
  const list=$('libraryList'),create=$('createDocBtn');if(!list||!create)return;
  if(!$('newCategory')){const l=document.createElement('label');l.innerHTML='Category<input id="newCategory" class="library-category-input" list="libraryCategoryList" value="Uncategorized" placeholder="e.g. Grade 10 Maths">';create.before(l);const dl=document.createElement('datalist');dl.id='libraryCategoryList';l.after(dl);}
  if(!$('sharedLibraryTools')){const t=document.createElement('div');t.id='sharedLibraryTools';t.className='shared-library-tools';t.innerHTML='<input id="librarySearch" class="library-search" placeholder="Search whole library…"><select id="libraryCategoryFilter"><option value="">All categories</option></select><button id="masterBackupBtn" class="btn compact" type="button">Master backup</button><span id="masterProgress" class="master-progress"></span>';list.before(t);const n=document.createElement('div');n.className='shared-library-note';n.textContent='Shared teacher library — all signed-in teacher profiles see the same PDFs and categories.';t.after(n);$('librarySearch').addEventListener('input',render);$('libraryCategoryFilter').addEventListener('change',render);$('masterBackupBtn').addEventListener('click',masterBackup);}
}

async function load(){const {data,error}=await supabase.from('snt_pdf_documents').select('*').order('updated_at',{ascending:false});if(error)throw error;docs=data||[];const cats=[...new Set(docs.map(d=>cat(d.category)))].sort();const f=$('libraryCategoryFilter'),dl=$('libraryCategoryList');if(f){const keep=f.value;f.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');f.value=cats.includes(keep)?keep:'';}if(dl)dl.innerHTML=cats.map(c=>`<option value="${esc(c)}"></option>`).join('');render();}

function render(){const list=$('libraryList');if(!list)return;const q=($('librarySearch')?.value||'').toLowerCase(),f=$('libraryCategoryFilter')?.value||'';const rows=docs.filter(d=>{const c=cat(d.category);return(!f||c===f)&&(!q||`${d.title||''} ${d.drive_file_id||''} ${c}`.toLowerCase().includes(q));});const groups={};for(const d of rows)(groups[cat(d.category)]??=[]).push(d);list.innerHTML=Object.keys(groups).sort().map(c=>`<section class="library-category-group"><div class="library-category-head"><span>${esc(c)}</span><span class="library-category-count">${groups[c].length} PDF${groups[c].length===1?'':'s'}</span></div>${groups[c].map(d=>`<div class="lib-row"><div class="lib-main"><strong>${esc(d.title)}</strong><small>Drive file ${esc(d.drive_file_id)}</small><span class="lib-category-pill">${esc(cat(d.category))}</span></div><div class="lib-actions"><button class="btn compact" data-open="${d.id}">Open</button><button class="btn compact" data-copy="${d.id}">Copy link</button><button class="btn compact category-btn" data-cat="${d.id}">Category</button><button class="btn compact" data-revoke="${d.id}">${d.student_link_enabled?'Revoke':'Enable'}</button><button class="btn compact" data-rotate="${d.id}">New link</button><button class="btn compact danger-text" data-delete="${d.id}">Delete</button></div></div>`).join('')}</section>`).join('')||'<p>No PDFs match this view.</p>';list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>act(b)));}

async function act(b){const id=b.dataset.open||b.dataset.copy||b.dataset.cat||b.dataset.revoke||b.dataset.rotate||b.dataset.delete,d=docs.find(x=>x.id===id);if(!d)return;if(b.dataset.open){location.href=`./teacher.html?id=${encodeURIComponent(d.id)}`;return;}if(b.dataset.copy){await copy(studentUrl(d));status('Student link copied');return;}if(b.dataset.cat){const v=prompt('Category for this PDF:',cat(d.category));if(v===null)return;const {error}=await supabase.from('snt_pdf_documents').update({category:cat(v),updated_at:new Date().toISOString()}).eq('id',d.id);if(error)return status(error.message);await load();return;}if(b.dataset.revoke){await supabase.from('snt_pdf_documents').update({student_link_enabled:!d.student_link_enabled,updated_at:new Date().toISOString()}).eq('id',d.id);await load();return;}if(b.dataset.rotate&&confirm('Create a new student link? The old link will stop working.')){await supabase.from('snt_pdf_documents').update({student_token:randomToken(),student_link_enabled:true,updated_at:new Date().toISOString()}).eq('id',d.id);await load();return;}if(b.dataset.delete&&confirm(`Delete “${d.title}” and all its SNT data?`)){const {error}=await supabase.from('snt_pdf_documents').delete().eq('id',d.id);if(error)return status(error.message);await load();}}

async function createDoc(e){e.preventDefault();e.stopImmediatePropagation();const title=$('newTitle')?.value.trim(),url=$('newDriveUrl')?.value.trim(),id=driveId(url),category=cat($('newCategory')?.value);if(!title||!id)return status('Enter a title and valid Google Drive PDF link.');await load();const exists=docs.find(d=>d.drive_file_id===id);if(exists){if(confirm('This PDF is already in the shared library. Open it?'))location.href=`./teacher.html?id=${encodeURIComponent(exists.id)}`;return;}const {data:{user}}=await supabase.auth.getUser();if(!user)return status('Teacher sign-in required.');const {data,error}=await supabase.from('snt_pdf_documents').insert({owner_id:user.id,title,category,drive_file_id:id,drive_share_url:url,student_token:randomToken(),student_link_enabled:true,student_hooked:true,live_board_no:1}).select('*').single();if(error)return status(error.message);const {error:be}=await supabase.from('snt_pdf_boards').insert({document_id:data.id,board_no:1,title:'Permanent board',text_content:'',objects:[],board_scope:'global',page_no:1,is_permanent:true});if(be)return status(be.message);location.href=`./teacher.html?id=${encodeURIComponent(data.id)}`;}

async function masterBackup(){if(!window.JSZip)return status('Backup library missing. Refresh once.');try{await load();if(!docs.length)return status('Library is empty.');const zip=new JSZip(),master={format:'SNT_PDF_ANNOTATOR_MASTER_BACKUP',version:1,app_version:'3.11',exported_at:new Date().toISOString(),documents:[]};for(let di=0;di<docs.length;di++){const d=docs[di];status(`Master backup ${di+1}/${docs.length}: ${d.title}`);const [{data:pages,error:pe},{data:boards,error:be},{data:images,error:ie},gallery]=await Promise.all([supabase.from('snt_pdf_pages').select('page_no,objects,updated_at').eq('document_id',d.id).order('page_no'),supabase.from('snt_pdf_boards').select('board_no,title,text_content,objects,board_scope,page_no,is_permanent,updated_at').eq('document_id',d.id).order('board_no'),supabase.from('snt_pdf_board_images').select('id,board_no,image_name,mime_type,file_size,sort_no,created_at').eq('document_id',d.id).order('sort_no'),api(d.id,'gallery-state')]);if(pe)throw pe;if(be)throw be;if(ie)throw ie;const folder=`documents/${String(di+1).padStart(4,'0')}_${safe(d.title)}_${d.id}`,m={document:{title:d.title,category:cat(d.category),drive_file_id:d.drive_file_id,drive_share_url:d.drive_share_url,student_token:d.student_token,student_link_enabled:d.student_link_enabled!==false},pages:pages||[],boards:boards||[],gallery:gallery.gallery||gallery,images:[]};for(let i=0;i<(images||[]).length;i++){const im=images[i],r=await fetch(apiUrl(d.id,'image',{image:im.id}),{headers:await headers()});if(!r.ok)throw new Error(`Could not fetch image from ${d.title}`);const blob=await r.blob(),path=`images/${String(i+1).padStart(4,'0')}_${im.id}.${imageExt(im.mime_type||blob.type)}`;zip.file(`${folder}/${path}`,blob,{binary:true,compression:'STORE'});m.images.push({...im,old_id:im.id,backup_path:path});}zip.file(`${folder}/manifest.json`,JSON.stringify(m,null,2));master.documents.push({title:d.title,category:cat(d.category),drive_file_id:d.drive_file_id,folder});}zip.file('master-manifest.json',JSON.stringify(master,null,2));status('Packing master backup…');const blob=await zip.generateAsync({type:'blob',compression:'STORE'});download(blob,`SNT_MASTER_LIBRARY_${stamp()}.sntmaster`);status(`Master backup complete: ${docs.length} PDFs`);}catch(e){status('Master backup failed: '+(e?.message||e));alert('Master backup failed.\n\n'+(e?.message||e));}}

function bind(){ensureUI();$('createDocBtn')?.addEventListener('click',createDoc,{capture:true});$('libraryBtn')?.addEventListener('click',()=>setTimeout(load,100));const dlg=$('libraryDialog');if(dlg)new MutationObserver(()=>{if(dlg.open)load();}).observe(dlg,{attributes:true,attributeFilter:['open']});setTimeout(()=>{if(dlg?.open)load();},500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
