import { CONFIG } from "./config.js";
import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const pdfjsLib = window.pdfjsLib;
if (!pdfjsLib) throw new Error("PDF.js failed to load.");
pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";

const MODE = document.body.dataset.mode || "student";
const TEACHER = MODE === "teacher";
const supabase = createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_PUBLISHABLE_KEY);
const $ = id => document.getElementById(id);
const els = {
  loading:$("loading"), error:$("error"), workspace:$("workspace"), docTitle:$("docTitle"), contextText:$("contextText"),
  pdfScroller:$("pdfScroller"), canvasWrap:$("canvasWrap"), pdfCanvas:$("pdfCanvas"), overlayCanvas:$("overlayCanvas"),
  prevPage:$("prevPage"), nextPage:$("nextPage"), pageInput:$("pageInput"), pageCount:$("pageCount"),
  zoomOut:$("zoomOut"), zoomIn:$("zoomIn"), fitPage:$("fitPage"),
  boardPanel:$("boardPanel"), toggleBoard:$("toggleBoard"), boardCanvas:$("boardCanvas"), boardText:$("boardText"), boardLabel:$("boardLabel"),
  boardPrev:$("boardPrev"), boardNext:$("boardNext"), boardAdd:$("boardAdd"), statusText:$("statusText"), liveText:$("liveText"),
  toolButtons:[...document.querySelectorAll("[data-tool]")], widthInput:$("widthInput"), colorInput:$("colorInput"), undoBtn:$("undoBtn"), redoBtn:$("redoBtn"), deleteSelected:$("deleteSelected"),
  loginPanel:$("loginPanel"), loginForm:$("loginForm"), emailInput:$("emailInput"), passwordInput:$("passwordInput"), signOutBtn:$("signOutBtn"),
  libraryBtn:$("libraryBtn"), libraryDialog:$("libraryDialog"), libraryList:$("libraryList"), createDocBtn:$("createDocBtn"), newTitle:$("newTitle"), newDriveUrl:$("newDriveUrl"),
  copyStudentLink:$("copyStudentLink"), exportPdf:$("exportPdf")
};

const state = {
  token:null, session:null, doc:null, pdf:null, pageNo:1, scale:1.2, fit:true, rendering:false, pendingPage:null,
  pageObjects:[], boards:[], boardNo:1, boardObjects:[], revision:0, tool:"pen", activeSurface:"pdf", pointer:null,
  selectedId:null, clipboard:null, undo:[], redo:[], saveTimer:null, boardSaveTimer:null, boardTextTimer:null, pollTimer:null,
  boardOpen:TEACHER && window.innerWidth > 1000
};

function showError(msg){ if(els.loading)els.loading.classList.add("hidden"); if(els.workspace)els.workspace.classList.add("hidden"); if(els.error){els.error.textContent=msg;els.error.classList.remove("hidden");} }
function showLoading(msg="Loading…"){ if(els.error)els.error.classList.add("hidden"); if(els.loading){els.loading.textContent=msg;els.loading.classList.remove("hidden");} }
function setStatus(msg){ if(els.statusText)els.statusText.textContent=msg; }
function randomToken(){ const a=new Uint8Array(32);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,""); }
function uuid(){ if(crypto.randomUUID)return crypto.randomUUID();const a=new Uint8Array(16);crypto.getRandomValues(a);a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=[...a].map(x=>x.toString(16).padStart(2,"0")).join("");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`; }
function extractDriveId(value=""){ const s=String(value).trim();let m=s.match(/\/file\/d\/([A-Za-z0-9_-]+)/);if(m)return m[1];m=s.match(/[?&]id=([A-Za-z0-9_-]+)/);if(m)return m[1];if(/^[A-Za-z0-9_-]{20,}$/.test(s))return s;return ""; }
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function clone(v){return JSON.parse(JSON.stringify(v));}

function apiUrl(action, extra={}){
  const u=new URL(`${CONFIG.SUPABASE_URL.replace(/\/$/,"")}/functions/v1/${CONFIG.API_FUNCTION}`);u.searchParams.set("action",action);
  for(const [k,v] of Object.entries(extra))if(v!==undefined&&v!==null)u.searchParams.set(k,String(v));
  if(TEACHER&&state.doc?.id)u.searchParams.set("doc",state.doc.id);return u.toString();
}
async function api(action, extra={}){
  const headers={apikey:CONFIG.SUPABASE_PUBLISHABLE_KEY};
  if(TEACHER&&state.session?.access_token)headers.Authorization=`Bearer ${state.session.access_token}`;
  if(!TEACHER&&state.token)headers["x-viewer-token"]=state.token;
  const r=await fetch(apiUrl(action,extra),{headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;
}
function pdfHeaders(){const h={apikey:CONFIG.SUPABASE_PUBLISHABLE_KEY};if(TEACHER&&state.session?.access_token)h.Authorization=`Bearer ${state.session.access_token}`;if(!TEACHER&&state.token)h["x-viewer-token"]=state.token;return h;}
function studentUrl(doc=state.doc){const u=new URL("./index.html",location.href);u.hash=`t=${doc.student_token}`;return u.href;}
async function copyText(text){try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement("textarea");t.value=text;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove();}}
function curColor(){return els.colorInput?.value||"#1f2937";} function curWidth(){return Number(els.widthInput?.value||4);}

function remember(){if(!TEACHER)return;const snap=state.activeSurface==="board"?clone(state.boardObjects):clone(state.pageObjects);state.undo.push({surface:state.activeSurface,data:snap});if(state.undo.length>60)state.undo.shift();state.redo=[];}
function applyHistory(from,to){const item=from.pop();if(!item)return;const current=item.surface==="board"?clone(state.boardObjects):clone(state.pageObjects);to.push({surface:item.surface,data:current});state.activeSurface=item.surface;if(item.surface==="board"){state.boardObjects=clone(item.data);saveBoardSoon();drawBoard();}else{state.pageObjects=clone(item.data);savePageSoon();drawOverlay();}}

function norm(evt,canvas){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(evt.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(evt.clientY-r.top)/r.height))};}
function distPointSegment(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,wx=p.x-a.x,wy=p.y-a.y,c1=vx*wx+vy*wy;if(c1<=0)return Math.hypot(p.x-a.x,p.y-a.y);const c2=vx*vx+vy*vy;if(c2<=c1)return Math.hypot(p.x-b.x,p.y-b.y);const t=c1/c2;return Math.hypot(p.x-(a.x+t*vx),p.y-(a.y+t*vy));}
function hitTest(objects,p){for(let i=objects.length-1;i>=0;i--){const o=objects[i];if(o.type==="text"&&Math.hypot(p.x-o.x,p.y-o.y)<.045)return o;if(o.type==="pen"||o.type==="highlighter"){const pts=o.points||[];for(let j=1;j<pts.length;j++)if(distPointSegment(p,pts[j-1],pts[j])<.025)return o;}else if(["line","arrow"].includes(o.type)){if(distPointSegment(p,{x:o.x1,y:o.y1},{x:o.x2,y:o.y2})<.025)return o;}else if(["rect","ellipse"].includes(o.type)){const minx=Math.min(o.x1,o.x2)-.025,maxx=Math.max(o.x1,o.x2)+.025,miny=Math.min(o.y1,o.y2)-.025,maxy=Math.max(o.y1,o.y2)+.025;if(p.x>=minx&&p.x<=maxx&&p.y>=miny&&p.y<=maxy)return o;}}return null;}
function translateObject(o,dx,dy){const clamp=v=>Math.max(0,Math.min(1,v));if(o.points)o.points=o.points.map(p=>({x:clamp(p.x+dx),y:clamp(p.y+dy)}));for(const k of ["x","x1","x2"])if(typeof o[k]==="number")o[k]=clamp(o[k]+dx);for(const k of ["y","y1","y2"])if(typeof o[k]==="number")o[k]=clamp(o[k]+dy);}

function objectBounds(o){if(o.type==="text")return{x1:o.x,y1:o.y,x2:o.x+.08,y2:o.y+.035};if(o.points?.length){const xs=o.points.map(p=>p.x),ys=o.points.map(p=>p.y);return{x1:Math.min(...xs),y1:Math.min(...ys),x2:Math.max(...xs),y2:Math.max(...ys)};}return{x1:Math.min(o.x1,o.x2),y1:Math.min(o.y1,o.y2),x2:Math.max(o.x1,o.x2),y2:Math.max(o.y1,o.y2)};}
function drawObject(ctx,o,canvas,selected=false){
  const w=canvas.width,h=canvas.height,X=x=>x*w,Y=y=>y*h;ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle=o.color||"#1f2937";ctx.fillStyle=o.color||"#1f2937";const ratio=w/(canvas.getBoundingClientRect().width||w);ctx.lineWidth=Math.max(1,(o.width||4)*ratio);ctx.globalAlpha=o.type==="highlighter"?.28:1;
  if(o.type==="pen"||o.type==="highlighter"){const pts=o.points||[];if(pts.length){ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(X(p.x),Y(p.y)):ctx.moveTo(X(p.x),Y(p.y)));ctx.stroke();}}
  else if(o.type==="text"){ctx.globalAlpha=1;ctx.font=`${Math.max(14,(o.fontSize||18)*ratio)}px system-ui,sans-serif`;ctx.fillText(o.text||"",X(o.x),Y(o.y));}
  else if(o.type==="line"||o.type==="arrow"){ctx.beginPath();ctx.moveTo(X(o.x1),Y(o.y1));ctx.lineTo(X(o.x2),Y(o.y2));ctx.stroke();if(o.type==="arrow"){const ang=Math.atan2(Y(o.y2)-Y(o.y1),X(o.x2)-X(o.x1)),len=12*ratio;ctx.beginPath();ctx.moveTo(X(o.x2),Y(o.y2));ctx.lineTo(X(o.x2)-len*Math.cos(ang-Math.PI/6),Y(o.y2)-len*Math.sin(ang-Math.PI/6));ctx.moveTo(X(o.x2),Y(o.y2));ctx.lineTo(X(o.x2)-len*Math.cos(ang+Math.PI/6),Y(o.y2)-len*Math.sin(ang+Math.PI/6));ctx.stroke();}}
  else if(o.type==="rect")ctx.strokeRect(X(Math.min(o.x1,o.x2)),Y(Math.min(o.y1,o.y2)),Math.abs(o.x2-o.x1)*w,Math.abs(o.y2-o.y1)*h);
  else if(o.type==="ellipse"){ctx.beginPath();ctx.ellipse(X((o.x1+o.x2)/2),Y((o.y1+o.y2)/2),Math.abs(o.x2-o.x1)*w/2,Math.abs(o.y2-o.y1)*h/2,0,0,Math.PI*2);ctx.stroke();}
  if(selected){const b=objectBounds(o);ctx.globalAlpha=1;ctx.setLineDash([6*ratio,5*ratio]);ctx.strokeStyle="#147a5a";ctx.lineWidth=2*ratio;ctx.strokeRect(X(b.x1)-5*ratio,Y(b.y1)-5*ratio,Math.max(12*ratio,X(b.x2-b.x1)+10*ratio),Math.max(12*ratio,Y(b.y2-b.y1)+10*ratio));}ctx.restore();
}
function drawOverlay(){const c=els.overlayCanvas,ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);for(const o of state.pageObjects)drawObject(ctx,o,c,o.id===state.selectedId&&state.activeSurface==="pdf");}
function drawBoard(){const c=els.boardCanvas,ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle="#e4e9ee";ctx.lineWidth=1;for(let y=70;y<c.height;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();}ctx.restore();for(const o of state.boardObjects)drawObject(ctx,o,c,o.id===state.selectedId&&state.activeSurface==="board");}
function activeObjects(){return state.activeSurface==="board"?state.boardObjects:state.pageObjects;}
function setTool(tool){state.tool=tool;state.selectedId=null;els.toolButtons.forEach(b=>b.classList.toggle("active",b.dataset.tool===tool));els.canvasWrap?.classList.toggle("hand",tool==="hand");drawOverlay();drawBoard();}

function pointerDown(evt,surface){
  if(!TEACHER)return;state.activeSurface=surface;const canvas=surface==="board"?els.boardCanvas:els.overlayCanvas,objects=surface==="board"?state.boardObjects:state.pageObjects,p=norm(evt,canvas);if(state.tool==="hand")return;
  if(state.tool==="select"){const hit=hitTest(objects,p);state.selectedId=hit?.id||null;drawOverlay();drawBoard();if(hit){remember();state.pointer={surface,id:hit.id,last:p,kind:"move",pointerId:evt.pointerId};canvas.setPointerCapture?.(evt.pointerId);}return;}
  if(state.tool==="eraser"){const hit=hitTest(objects,p);if(hit){remember();const i=objects.findIndex(x=>x.id===hit.id);objects.splice(i,1);state.selectedId=null;surface==="board"?saveBoardSoon():savePageSoon();surface==="board"?drawBoard():drawOverlay();}return;}
  if(state.tool==="text"){const text=prompt("Text to add:");if(!text)return;remember();objects.push({id:uuid(),type:"text",x:p.x,y:p.y,text:text.slice(0,600),color:curColor(),fontSize:Math.max(14,curWidth()*5)});surface==="board"?saveBoardSoon():savePageSoon();surface==="board"?drawBoard():drawOverlay();return;}
  remember();let o;if(state.tool==="pen"||state.tool==="highlighter")o={id:uuid(),type:state.tool,points:[p],color:curColor(),width:curWidth()};else o={id:uuid(),type:state.tool,x1:p.x,y1:p.y,x2:p.x,y2:p.y,color:curColor(),width:curWidth()};objects.push(o);state.pointer={surface,id:o.id,last:p,kind:"draw",pointerId:evt.pointerId};canvas.setPointerCapture?.(evt.pointerId);
}
function pointerMove(evt,surface){const ps=state.pointer;if(!TEACHER||!ps||ps.surface!==surface||ps.pointerId!==evt.pointerId)return;const canvas=surface==="board"?els.boardCanvas:els.overlayCanvas,objects=surface==="board"?state.boardObjects:state.pageObjects,p=norm(evt,canvas),o=objects.find(x=>x.id===ps.id);if(!o)return;if(ps.kind==="move"){translateObject(o,p.x-ps.last.x,p.y-ps.last.y);ps.last=p;}else if(o.type==="pen"||o.type==="highlighter"){const last=o.points[o.points.length-1];if(Math.hypot(p.x-last.x,p.y-last.y)>.0015)o.points.push(p);}else{o.x2=p.x;o.y2=p.y;}surface==="board"?drawBoard():drawOverlay();}
function pointerUp(evt,surface){const ps=state.pointer;if(!TEACHER||!ps||ps.surface!==surface||ps.pointerId!==evt.pointerId)return;state.pointer=null;surface==="board"?saveBoardSoon():savePageSoon();}

function savePageSoon(){if(!TEACHER||!state.doc)return;clearTimeout(state.saveTimer);setStatus("Saving…");state.saveTimer=setTimeout(async()=>{try{const {error}=await supabase.from("snt_pdf_pages").upsert({document_id:state.doc.id,page_no:state.pageNo,objects:state.pageObjects,updated_at:new Date().toISOString()},{onConflict:"document_id,page_no"});if(error)throw error;setStatus("Saved");}catch(e){setStatus("Save failed: "+e.message);}},320);}
function saveBoardSoon(){if(!TEACHER||!state.doc)return;clearTimeout(state.boardSaveTimer);setStatus("Saving notepad…");state.boardSaveTimer=setTimeout(async()=>{try{const {error}=await supabase.from("snt_pdf_boards").upsert({document_id:state.doc.id,page_no:state.pageNo,board_no:state.boardNo,title:`Board ${state.boardNo}`,text_content:els.boardText.value||"",objects:state.boardObjects,updated_at:new Date().toISOString()},{onConflict:"document_id,page_no,board_no"});if(error)throw error;setStatus("Saved");await loadTeacherBoards(false);}catch(e){setStatus("Save failed: "+e.message);}},320);}
function saveBoardTextSoon(){if(!TEACHER)return;clearTimeout(state.boardTextTimer);state.boardTextTimer=setTimeout(saveBoardSoon,300);}

async function loadTeacherPageData(){const {data,error}=await supabase.from("snt_pdf_pages").select("objects").eq("document_id",state.doc.id).eq("page_no",state.pageNo).maybeSingle();if(error)throw error;state.pageObjects=Array.isArray(data?.objects)?data.objects:[];state.selectedId=null;state.undo=[];state.redo=[];drawOverlay();}
async function loadTeacherBoards(reset=true){const {data,error}=await supabase.from("snt_pdf_boards").select("*").eq("document_id",state.doc.id).eq("page_no",state.pageNo).order("board_no");if(error)throw error;state.boards=data||[];if(!state.boards.length){const {error:e2}=await supabase.from("snt_pdf_boards").insert({document_id:state.doc.id,page_no:state.pageNo,board_no:1,title:"Board 1",text_content:"",objects:[]});if(e2)throw e2;state.boards=[{board_no:1,title:"Board 1",text_content:"",objects:[]}];}if(reset){if(!state.boards.some(x=>x.board_no===state.boardNo))state.boardNo=state.boards[0].board_no;loadBoardFromList();}}
function loadBoardFromList(){const b=state.boards.find(x=>x.board_no===state.boardNo)||{board_no:state.boardNo,title:`Board ${state.boardNo}`,text_content:"",objects:[]};state.boardObjects=Array.isArray(b.objects)?clone(b.objects):[];els.boardText.value=b.text_content||"";els.boardLabel.textContent=`Page ${state.pageNo} • ${b.title||`Board ${state.boardNo}`}`;state.selectedId=null;drawBoard();}
async function reloadStudentCurrent(){const p=await api("page",{page:state.pageNo});state.pageObjects=Array.isArray(p.objects)?p.objects:[];drawOverlay();const b=await api("boards",{page:state.pageNo});state.boards=b.boards||[];if(!state.boards.length)state.boards=[{board_no:1,title:"Board 1",text_content:"",objects:[]}];if(!state.boards.some(x=>x.board_no===state.boardNo))state.boardNo=state.boards[0].board_no;loadBoardFromList();}
async function loadPageData(){if(TEACHER){await loadTeacherPageData();state.boardNo=1;await loadTeacherBoards(true);}else await reloadStudentCurrent();}

async function renderPage(n){if(!state.pdf)return;if(state.rendering){state.pendingPage=n;return;}state.rendering=true;try{n=Math.max(1,Math.min(state.pdf.numPages,Number(n)||1));const page=await state.pdf.getPage(n);let scale=state.scale;if(state.fit){const base=page.getViewport({scale:1}),available=Math.max(280,els.pdfScroller.clientWidth-20);scale=Math.max(.45,Math.min(2.5,available/base.width));state.scale=scale;}const viewport=page.getViewport({scale}),dpr=Math.min(window.devicePixelRatio||1,2);for(const c of [els.pdfCanvas,els.overlayCanvas]){c.width=Math.floor(viewport.width*dpr);c.height=Math.floor(viewport.height*dpr);c.style.width=`${viewport.width}px`;c.style.height=`${viewport.height}px`;}els.canvasWrap.style.width=`${viewport.width}px`;els.canvasWrap.style.height=`${viewport.height}px`;const ctx=els.pdfCanvas.getContext("2d",{alpha:false});await page.render({canvasContext:ctx,viewport,transform:dpr===1?null:[dpr,0,0,dpr,0,0]}).promise;state.pageNo=n;els.pageInput.value=String(n);els.pageCount.textContent=`/ ${state.pdf.numPages}`;els.prevPage.disabled=n<=1;els.nextPage.disabled=n>=state.pdf.numPages;if(TEACHER)await supabase.from("snt_pdf_documents").update({live_page:n,updated_at:new Date().toISOString()}).eq("id",state.doc.id);await loadPageData();drawOverlay();}finally{state.rendering=false;if(state.pendingPage!==null){const p=state.pendingPage;state.pendingPage=null;renderPage(p);}}}
async function loadPdf(){showLoading("Loading Google Drive PDF…");const task=pdfjsLib.getDocument({url:apiUrl("pdf"),httpHeaders:pdfHeaders(),rangeChunkSize:262144,disableAutoFetch:true,disableStream:false});state.pdf=await task.promise;await renderPage(state.pageNo);}

function bindCommon(){
  els.prevPage?.addEventListener("click",()=>renderPage(state.pageNo-1));els.nextPage?.addEventListener("click",()=>renderPage(state.pageNo+1));els.pageInput?.addEventListener("change",()=>renderPage(els.pageInput.value));
  els.zoomOut?.addEventListener("click",()=>{state.fit=false;state.scale=Math.max(.4,state.scale-.15);renderPage(state.pageNo);});els.zoomIn?.addEventListener("click",()=>{state.fit=false;state.scale=Math.min(3.5,state.scale+.15);renderPage(state.pageNo);});els.fitPage?.addEventListener("click",()=>{state.fit=true;renderPage(state.pageNo);});
  els.toggleBoard?.addEventListener("click",()=>{state.boardOpen=!state.boardOpen;els.boardPanel.classList.toggle("open",state.boardOpen);els.boardPanel.style.display=state.boardOpen?"":"none";});
  els.boardPrev?.addEventListener("click",()=>{const arr=state.boards.map(x=>x.board_no).sort((a,b)=>a-b),i=arr.indexOf(state.boardNo);if(i>0){state.boardNo=arr[i-1];loadBoardFromList();}});els.boardNext?.addEventListener("click",()=>{const arr=state.boards.map(x=>x.board_no).sort((a,b)=>a-b),i=arr.indexOf(state.boardNo);if(i>=0&&i<arr.length-1){state.boardNo=arr[i+1];loadBoardFromList();}});
  window.addEventListener("resize",()=>{if(state.fit&&state.pdf){clearTimeout(window.__sntResize);window.__sntResize=setTimeout(()=>renderPage(state.pageNo),220);}});
}
function deleteSelected(){if(!state.selectedId)return;remember();const arr=activeObjects(),i=arr.findIndex(x=>x.id===state.selectedId);if(i>=0)arr.splice(i,1);state.selectedId=null;state.activeSurface==="board"?saveBoardSoon():savePageSoon();drawOverlay();drawBoard();}
function bindTeacher(){
  els.toolButtons.forEach(b=>b.addEventListener("click",()=>setTool(b.dataset.tool)));for(const [canvas,surface] of [[els.overlayCanvas,"pdf"],[els.boardCanvas,"board"]]){canvas.addEventListener("pointerdown",e=>pointerDown(e,surface));canvas.addEventListener("pointermove",e=>pointerMove(e,surface));canvas.addEventListener("pointerup",e=>pointerUp(e,surface));canvas.addEventListener("pointercancel",e=>pointerUp(e,surface));}
  els.undoBtn?.addEventListener("click",()=>applyHistory(state.undo,state.redo));els.redoBtn?.addEventListener("click",()=>applyHistory(state.redo,state.undo));els.deleteSelected?.addEventListener("click",deleteSelected);els.boardText?.addEventListener("input",saveBoardTextSoon);
  els.boardAdd?.addEventListener("click",async()=>{const max=Math.max(0,...state.boards.map(x=>x.board_no)),no=max+1;const {error}=await supabase.from("snt_pdf_boards").insert({document_id:state.doc.id,page_no:state.pageNo,board_no:no,title:`Board ${no}`,text_content:"",objects:[]});if(error)return setStatus(error.message);await loadTeacherBoards(false);state.boardNo=no;loadBoardFromList();});
  els.copyStudentLink?.addEventListener("click",async()=>{await copyText(studentUrl());setStatus("Student link copied");});els.exportPdf?.addEventListener("click",exportAnnotatedPdf);els.libraryBtn?.addEventListener("click",openLibrary);els.signOutBtn?.addEventListener("click",async()=>{await supabase.auth.signOut();location.href="./teacher.html";});els.createDocBtn?.addEventListener("click",createDocumentFromForm);
  document.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA"].includes(document.activeElement?.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?applyHistory(state.redo,state.undo):applyHistory(state.undo,state.redo);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();applyHistory(state.redo,state.undo);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="c"){const o=activeObjects().find(x=>x.id===state.selectedId);if(o)state.clipboard=clone(o);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="v"&&state.clipboard){e.preventDefault();remember();const o=clone(state.clipboard);o.id=uuid();translateObject(o,.025,.025);activeObjects().push(o);state.selectedId=o.id;state.activeSurface==="board"?saveBoardSoon():savePageSoon();drawOverlay();drawBoard();}if(e.key==="Delete"||e.key==="Backspace")deleteSelected();});
}

async function exportAnnotatedPdf(){if(!TEACHER||!window.PDFLib)return;try{setStatus("Preparing export…");const r=await fetch(apiUrl("pdf"),{headers:pdfHeaders()});if(!r.ok)throw new Error("Could not download source PDF.");const bytes=await r.arrayBuffer();const {PDFDocument,rgb,StandardFonts}=window.PDFLib,pdf=await PDFDocument.load(bytes),font=await pdf.embedFont(StandardFonts.Helvetica);const {data:rows,error}=await supabase.from("snt_pdf_pages").select("page_no,objects").eq("document_id",state.doc.id);if(error)throw error;const hex=h=>{const m=(h||"#1f2937").replace("#","");return rgb(parseInt(m.slice(0,2),16)/255,parseInt(m.slice(2,4),16)/255,parseInt(m.slice(4,6),16)/255);};for(const row of rows||[]){const page=pdf.getPage(row.page_no-1);if(!page)continue;const {width,height}=page.getSize(),X=x=>x*width,Y=y=>(1-y)*height;for(const o of row.objects||[]){const color=hex(o.color),th=Math.max(.6,(o.width||4)*.75),opacity=o.type==="highlighter"?.28:1;if(o.type==="pen"||o.type==="highlighter"){const pts=o.points||[];for(let i=1;i<pts.length;i++)page.drawLine({start:{x:X(pts[i-1].x),y:Y(pts[i-1].y)},end:{x:X(pts[i].x),y:Y(pts[i].y)},thickness:th,color,opacity});}else if(o.type==="text")page.drawText(o.text||"",{x:X(o.x),y:Y(o.y),size:Math.max(8,(o.fontSize||18)*.75),font,color});else if(o.type==="line"||o.type==="arrow"){page.drawLine({start:{x:X(o.x1),y:Y(o.y1)},end:{x:X(o.x2),y:Y(o.y2)},thickness:th,color});if(o.type==="arrow"){const x1=X(o.x1),y1=Y(o.y1),x2=X(o.x2),y2=Y(o.y2),ang=Math.atan2(y2-y1,x2-x1),len=10;for(const a of [ang+Math.PI*.82,ang-Math.PI*.82])page.drawLine({start:{x:x2,y:y2},end:{x:x2+len*Math.cos(a),y:y2+len*Math.sin(a)},thickness:th,color});}}else if(o.type==="rect")page.drawRectangle({x:X(Math.min(o.x1,o.x2)),y:Y(Math.max(o.y1,o.y2)),width:Math.abs(o.x2-o.x1)*width,height:Math.abs(o.y2-o.y1)*height,borderColor:color,borderWidth:th});else if(o.type==="ellipse")page.drawEllipse({x:X((o.x1+o.x2)/2),y:Y((o.y1+o.y2)/2),xScale:Math.abs(o.x2-o.x1)*width/2,yScale:Math.abs(o.y2-o.y1)*height/2,borderColor:color,borderWidth:th});}}
    const out=await pdf.save(),blob=new Blob([out],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${state.doc.title.replace(/[^A-Za-z0-9_-]+/g,"_")}_annotated.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);setStatus("Exported");}catch(e){setStatus("Export failed: "+e.message);}}

async function refreshLibrary(){const {data,error}=await supabase.from("snt_pdf_documents").select("*").order("updated_at",{ascending:false});if(error)throw error;els.libraryList.innerHTML=(data||[]).map(d=>`<div class="lib-row"><div class="lib-main"><strong>${escapeHtml(d.title)}</strong><small>Google Drive PDF</small></div><div class="lib-actions"><button class="btn compact" data-open="${d.id}">Open</button><button class="btn compact" data-copy="${d.id}">Copy link</button><button class="btn compact" data-revoke="${d.id}">${d.student_link_enabled?"Revoke":"Enable"}</button><button class="btn compact" data-rotate="${d.id}">New link</button><button class="btn compact" data-delete="${d.id}">Delete</button></div></div>`).join("")||"<p>No PDFs yet.</p>";els.libraryList.querySelectorAll("button").forEach(b=>b.addEventListener("click",async()=>{const id=b.dataset.open||b.dataset.copy||b.dataset.revoke||b.dataset.rotate||b.dataset.delete,d=(data||[]).find(x=>x.id===id);if(!d)return;if(b.dataset.open){els.libraryDialog.close();await openTeacherDocument(d);}if(b.dataset.copy){await copyText(studentUrl(d));setStatus("Student link copied");}if(b.dataset.revoke){await supabase.from("snt_pdf_documents").update({student_link_enabled:!d.student_link_enabled}).eq("id",d.id);await refreshLibrary();}if(b.dataset.rotate){if(confirm("Create a new student link? The old link will stop working.")){await supabase.from("snt_pdf_documents").update({student_token:randomToken(),student_link_enabled:true}).eq("id",d.id);await refreshLibrary();}}if(b.dataset.delete){if(confirm(`Delete "${d.title}" and all annotations/notepads?`)){await supabase.from("snt_pdf_documents").delete().eq("id",d.id);if(state.doc?.id===d.id)location.href="./teacher.html";else await refreshLibrary();}}}));}
async function openLibrary(){await refreshLibrary();els.libraryDialog.showModal();}
async function createDocumentFromForm(){const title=els.newTitle.value.trim(),url=els.newDriveUrl.value.trim(),fileId=extractDriveId(url);if(!title||!fileId)return setStatus("Enter a title and valid Google Drive PDF link.");const {data:{user}}=await supabase.auth.getUser();if(!user)return;const row={owner_id:user.id,title,drive_file_id:fileId,drive_share_url:url,student_token:randomToken(),student_link_enabled:true};const {data,error}=await supabase.from("snt_pdf_documents").insert(row).select("*").single();if(error){setStatus(error.message);return;}await supabase.from("snt_pdf_boards").insert({document_id:data.id,page_no:1,board_no:1,title:"Board 1",text_content:"",objects:[]});els.newTitle.value="";els.newDriveUrl.value="";els.libraryDialog.close();await openTeacherDocument(data);}
async function openTeacherDocument(doc){state.doc=doc;state.pageNo=Math.max(1,Number(doc.live_page||1));state.revision=Number(doc.revision||0);els.docTitle.textContent=doc.title;els.contextText.textContent="Teacher • autosaves to Supabase";history.replaceState(null,"",`./teacher.html?id=${encodeURIComponent(doc.id)}`);await loadPdf();els.loading.classList.add("hidden");els.workspace.classList.remove("hidden");els.boardPanel.style.display=state.boardOpen?"":"none";}
async function handleDriveQuery(){const params=new URLSearchParams(location.search),drive=params.get("drive");if(!drive)return false;const fileId=extractDriveId(drive);if(!fileId)return false;const {data}=await supabase.from("snt_pdf_documents").select("*").eq("drive_file_id",fileId).limit(1).maybeSingle();if(data){await openTeacherDocument(data);return true;}els.newDriveUrl.value=params.get("source")||`https://drive.google.com/file/d/${fileId}/view`;els.newTitle.value=params.get("title")||"Drive PDF";await openLibrary();return true;}

async function bootTeacher(){bindCommon();bindTeacher();const {data:{session}}=await supabase.auth.getSession();state.session=session;if(!session){els.loading.classList.add("hidden");els.loginPanel.classList.remove("hidden");els.loginForm.addEventListener("submit",async e=>{e.preventDefault();const {data,error}=await supabase.auth.signInWithPassword({email:els.emailInput.value.trim(),password:els.passwordInput.value});if(error){els.error.textContent=error.message;els.error.classList.remove("hidden");return;}state.session=data.session;els.loginPanel.classList.add("hidden");showLoading();await bootTeacherAfterLogin();});return;}await bootTeacherAfterLogin();}
async function bootTeacherAfterLogin(){const p=new URLSearchParams(location.search),id=p.get("id");if(id){const {data,error}=await supabase.from("snt_pdf_documents").select("*").eq("id",id).maybeSingle();if(error||!data)return showError("Document not found.");await openTeacherDocument(data);return;}if(await handleDriveQuery())return;els.loading.classList.add("hidden");await openLibrary();}
async function bootStudent(){bindCommon();state.token=new URLSearchParams(location.hash.replace(/^#/,"")).get("t");if(!state.token)return showError("This textbook link is missing or incomplete.");try{const init=await api("init");state.doc=init.document;state.revision=Number(init.document.revision||0);state.pageNo=1;els.docTitle.textContent=init.document.title;els.contextText.textContent="Teacher annotations • view only";state.boardOpen=false;await loadPdf();els.loading.classList.add("hidden");els.workspace.classList.remove("hidden");els.boardPanel.classList.remove("open");els.boardPanel.style.display="none";state.pollTimer=setInterval(async()=>{try{const s=await api("sync");if(Number(s.revision)!==state.revision){state.revision=Number(s.revision);els.liveText.textContent="Updated";await reloadStudentCurrent();setTimeout(()=>els.liveText.textContent="Live",700);}}catch{}},Number(CONFIG.STUDENT_POLL_MS||1500));}catch(e){showError(e.message);}}

if(TEACHER)bootTeacher().catch(e=>showError(e.message));else bootStudent().catch(e=>showError(e.message));
